### ISSUE TITLE
[Meta] Development SassDoc 2.0

### ISSUE THREAD

**Issue by FWeinb** [SassDoc/sassdoc#255]
Meta Issue for SassDoc 2.0:

* [x] Merge https://github.com/SassDoc/sassdoc-extras/pull/6
* [x] Update theme https://github.com/SassDoc/sassdoc-theme-default/issues/3, https://github.com/SassDoc/sassdoc-theme-default/issues/4
* [x] Delete sassdoc-theme-light repository https://github.com/SassDoc/sassdoc-theme-light/issues/47
* [x] Delete sassdoc-indexer repository https://github.com/SassDoc/sassdoc-indexer/issues/5
* [x] Delete sassdoc-filter repository https://github.com/SassDoc/sassdoc-filter/issues/12
* [x] Rename configuration file `.sassdocrc` (#189) 
* [x] Merge SassDoc#261
* [x] API decoupling (#231)
* [x] Glob expressions (#228)
* [x] `safe-wipe` options change
* [x] Always output in its directory (#302)
* [x] Full stream ahead (#287)
* [x] Finish the debug option (#311)
* [x] Externalize the syntax converter and its associated tests
* [x] Port the plugins to 2.0 API
* [x] Bring back `parse` (#318)
* [x] Use 6to5 instead of Traceur
* [x] Refactor `require` imports (#319)
* [x] [Update the website](https://github.com/SassDoc/sassdoc.github.io/issues?q=is:open+milestone:"SassDoc+2.0")
* [x] Test, test, test... (on libs, with different configs and environments)

**Comment by HugoGiraudel** [comment]
@SassDoc/owners @whyalix @kaishin Ideal deadline for SassDoc 2.0: **31 Janvier 2015**. We gotta release it at some point. :)

**Comment by valeriangalliat** [comment]
2.0.0-rc.14 tested successfully on FreeBSD (with SassyStrings).

* npm global installation.
* Regular documentation of a directory.
* Documentation from stdin into custom folder.
* Only parse and output JSON.
* Debug mode (no problem to find npm version on FreeBSD default setup BTW).
* Tests from Git version.

Needless to say it works for me on my regular setup (Arch Linux) with `sassdoc-theme-default`'s `scss` folder.

**Comment by FWeinb** [comment]
:+1: for this Test!

**Comment by HugoGiraudel** [comment]
Release coming closer. I'll take care of the branding.

**Comment by valeriangalliat** [comment]
I think we wan say SassDoc 2.0 have been tested quite a bit now. I'm ticking this box.

Also the coverage is not critical for 2.0 IMO.

**Comment by HugoGiraudel** [comment]
Article about SassDoc 2 is ready.
