### ISSUE TITLE
[Meta] Release SassDoc 2.0

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#330]
##### SassDoc/sassdoc
- [x] Remove npm 2 requirement and `engineStrict` from package
- [x] Update deps to stable `sassdoc-theme-default` `scss-comment-parser` 
- [x] Update `make publish` task
- [x] Release `2.0.0` 
- [x] Make `develop` the new `master`

##### SassDoc/sassdoc.github.io
- [x] Remove mentions of `npm update` and `@beta` is any.
- [x] Remove develop/beta related warnings and stuff
- [x] Publish website
- [x] Make `develop` the new `master`

##### SassDoc/sassdoc-theme-default
- [x] Release `2.0.0` 
- [x] Make `develop` the new `master`

##### SassDoc/sassdoc-extras
- [x] Release `2.0.0` 
- [x] Make `develop` the new `master`

##### SassDoc/scss-comments-parser
- [x] Release stable version

##### SassDoc/grunt-sassdoc
- [x] Update `sassdoc` dependency
- [x] Release `2.0.0` 
- [x] Make `develop` the new `master`

##### SassDoc/broccoli-sassdoc
- [x] Update `sassdoc` dependency
- [x] Release `2.0.0` 
- [x] Make `develop` the new `master`

##### SassDoc/gulp-sassdoc
- [x] Make `develop` and deprecated repo/package the default.

##### SassDoc/sassdocmeister

- [x] Update `sassdoc` dependency
- [x] Publish `gh-pages`

#### Twitter
- [x] Update avatar
- [x] Update background
- [ ] Announce it

**Comment by valeriangalliat** [comment]
>  Remove mentions of npm update and @beta is any.

I don't recall seeing `npm update` anywhere, and if we did good, all mentions to `@beta` are on [the `develop` repo](/SassDoc/develop) only (so we will discard it when merging `develop` branch in `master`.

> Remove develop/beta related warnings and stuff

Same here, normally the develop/beta warnings were added only in the `develop` repo, not the `develop` branch we will merge into `master`.

---

Just a reminder: when releasing SassDoc 2.0, we must not use `make publish`, because it adds `--tag beta`.

**Comment by pascalduez** [comment]
> Just a reminder: when releasing SassDoc 2.0, we must not use make publish, because it adds --tag beta.

I was thinking to remove the `--tag beta` from the task, so we can still benefit the others steps it does.

**Comment by valeriangalliat** [comment]
:+1:

**Comment by valeriangalliat** [comment]
Here's the script I plan for release (each step should still be executed manually to be sure!):

```sh
cd sassdoc
git checkout develop
git pull origin develop
vim package.json # Set version to 2.0.0
git push origin develop
make publish
git checkout master
git reset --hard develop
git push --force origin master
cd -

cd sassdoc.github.io
git checkout develop
git pull origin develop
git checkout master
git reset --hard develop
git push --force origin master
cd -

cd grunt-sassdoc
git checkout develop
git pull origin develop
vim package.json # Update `sassdoc` and set version to 2.0.0
git push origin develop
npm publish
git checkout master
git reset --hard develop
git push --force origin master
cd -

# Same as Grunt for Broccoli

cd sassdocmeister
git checkout master
git pull origin master
vim package.json # Update `sassdoc`
git push origin master
make pages
```

All good @SassDoc/owners?
