### ISSUE TITLE
[Meta] 2.3

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#484]
WIP
- [x] Poster annotations override #387, #410
- [x] Docs for poster annotations override SassDoc/sassdoc.github.io#120
- [ ]  Try to infer default values when compiling #304 
- [x] Update linting #400, #414, #447 
- [x]  Colour variables references sassdoc/sassdoc-theme-default#78 
- [x]  Docs for sassdoc-extras resolved values (2.4.0) SassDoc/sassdoc.github.io#123
- [ ]  Document CSS context parsing SassDoc/sassdoc.github.io#126
- [ ]  Add annotation aliases unit tests #446 
- [ ] ...
